### ISSUE TITLE
Max avatar size - Theme setting

### ISSUE THREAD

**Issue by Sinaloense** [hmrserver/Obsidian#1]
Hello.
Can you add the settings for the maximum avatar size (KB or MB)?

**Comment by hmrserver** [comment]
[This Commit](https://github.com/hmrserver/Obsidian/commit/e507f1e11c49cc4e85678fac05e49266a2d58458) would Allow Admins to set a MAX AVATAR SIZE.

**Comment by Sinaloense** [comment]
Thanks <3
