### ISSUE TITLE
Whenever when I put this theme the panel gets unresponsive

### ISSUE THREAD

**Issue by RaphaelD-N** [hmrserver/Obsidian#11]
Hello, whenever I choose this theme in my gamecp it gets unresponsive. First, it changes the theme but after for example I go to the dashboard the panel become unresponsive, so I need to move back to the default(Revolution) theme. It is because this theme is outdated? If so, how can we update this theme to work with the latest OGP panel?
Thank you,
Raphael

**Comment by hmrserver** [comment]
An screenshot/video would be appreciated.

**Comment by RaphaelD-N** [comment]
I'll do asap.

**Comment by RaphaelD-N** [comment]
So, here's the video(sorry for the late response)
https://youtu.be/wLgp9mSuhtc

**Comment by KillerRoi** [comment]
Do A Clean Re-Install and Lemme Know if That Fixes It For You, and in case you're not able to do so! contact me on discord KillerRoi#8795
