### ISSUE TITLE
Extra Settings Not Working And It Is Forcing Itself To Default!

### ISSUE THREAD

**Issue by KillerRoi** [hmrserver/Obsidian#13]
Hi There, I'm trying to change the loading bar settings to material but the panel doesn't let it! I've tried editing the config.xml file too but no luck! it just defaults to default!
![image](https://user-images.githubusercontent.com/54289708/89572727-2730ab00-d847-11ea-9c6a-f1ee0e518aa9.png)

**Comment by hmrserver** [comment]
Please try to give more info, like console logs, what is the file's permission of your config.xml file.
