### ISSUE TITLE
Blocked when changing to Obsidian

### ISSUE THREAD

**Issue by RisedSky** [hmrserver/Obsidian#15]
![image](https://user-images.githubusercontent.com/23197999/119209890-9bbc9980-baa9-11eb-8354-5b86bf371507.png)

The only way to fix this is to change the theme to another one as the Obisidan one is looping to the dashboard with nothing to show : 
![image](https://user-images.githubusercontent.com/23197999/119209936-e0483500-baa9-11eb-814c-67718de293b4.png)

**Comment by hmrserver** [comment]
Try to update your Open Game Panel and the theme to latest versions.

If the problem still persist then please post more details like your ogp version, browser console logs (while loading the very same page).
