### ISSUE TITLE
Add MySQL ICON  |  images/mysql.png

### ISSUE THREAD

**Issue by RouatbiH** [hmrserver/Obsidian#2]
![mysql](https://user-images.githubusercontent.com/23016064/32404921-03554c5a-c15b-11e7-9a46-059351545bdf.png)
![capture1](https://user-images.githubusercontent.com/23016064/32404933-6fe8e91c-c15b-11e7-832b-6781872f8f1d.PNG)

**Comment by hmrserver** [comment]
Done but haven't tested it since I don't know for which game its available.
Can you please download the latest version of the theme & recheck and report back ?

**Comment by RouatbiH** [comment]
ok
thank you

**Comment by lamjed001** [comment]
The Photo Doeas not show 
it is the same problem the old image show

**Comment by lamjed001** [comment]
Test It On MultiTheftAuto

**Comment by lamjed001** [comment]
change her name mysql.png to mysql_admin.png

**Comment by lamjed001** [comment]
![111111111](https://user-images.githubusercontent.com/23016064/32689584-db1aeffa-c6e7-11e7-8c53-e7b157530889.PNG)

**Comment by RouatbiH** [comment]
it false i don't know how to change mysql_admin image it is in administration or gamemanager module
