### ISSUE TITLE
Add ICONS | images/

### ISSUE THREAD

**Issue by RouatbiH** [hmrserver/Obsidian#4]
![gamemanager](https://user-images.githubusercontent.com/23016064/32689781-d5c96ad8-c6ea-11e7-931a-ab50d3d1d171.png) images/gamemanager.png
![master](https://user-images.githubusercontent.com/23016064/32689782-d5efa9f0-c6ea-11e7-94dd-534dd4b2312a.png) images/master.png
![editconfig](https://user-images.githubusercontent.com/23016064/32689783-d6148860-c6ea-11e7-8dce-2a7a1d04cd24.png) images/editconfig.png
![32689535-d8d2f4c8-c6e6-11e7-9759-cc66023760af](https://user-images.githubusercontent.com/23016064/32743332-5f87b686-c8ac-11e7-9031-1d0bb34a11cb.png) images/filemanager.png
![customfields](https://user-images.githubusercontent.com/23016064/33514064-b903c858-d74d-11e7-8b85-e08f63229dbd.png) images/customfields.png

**Comment by hmrserver** [comment]
Can you tell me about where I can see them ? And for which games ? I really need to see them personally too.

**Comment by RouatbiH** [comment]
Update Your OGP Version
Latest Update : 5df2685bf9e39e10ba2df046d78f25717fa4b8b4

filemanager in old version is txt.png but now is filemanager.png
so change your images/txt.png file to images/filemanager.png
filemanager is show in all games

**Comment by hmrserver** [comment]
I got the txt.png one but what about master.png  and editconfig.png.. for which game I would be able to see them in?

**Comment by RouatbiH** [comment]
change your images/txt.png file to images/filemanager.png

https://hmrworld.tk/panel/images/editconfig.png
https://hmrworld.tk/panel/images/filemanager.png
https://hmrworld.tk/panel/images/gamemanager.png
https://hmrworld.tk/panel/images/master.png

**Comment by hmrserver** [comment]
I mean practically for which games are all those icons being used ??

**Comment by RouatbiH** [comment]
These icon are not for games but for the Panel modules as are all others you found in the same folder, their respective names are pretty clear. gamemanager.png though is surely an icon not used anymore probably replaced by game_monitor.png (which could be deleted from GitHub but it doesn't hurt anyway).

First one is for Extra module EditConfigFiles and shown in the game server page as a button icon on the right side when module is installed and the game XML file for the panel has the required field to support the module, second one not used anymore I think but is replaced by game_monitor.png and shown in dashboard, and the third one is for Master Server Installation and show in game server page on right side as a button icon when Master Server Installation is available for this game server.
