### ISSUE TITLE
Theme not working on IPhones. 

### ISSUE THREAD

**Issue by floreich** [hmrserver/Obsidian#6]
I've tried to open up the panel with the theme on my iPhone but it doesn't show up correctly. Menu is missing

**Comment by floreich** [comment]
It doesnt work on mac at all

**Comment by floreich** [comment]
Could you please check that? It's highly annoying, as the vast majority of my users are Mac Users and therefore can't use the panel unless I change the theme

**Comment by hmrserver** [comment]
Some screenshots of the problem would be great.

**Comment by cTmoNe** [comment]
Can you fix?
