### ISSUE TITLE
add icon txt.png for litefm

### ISSUE THREAD

**Issue by RouatbiH** [hmrserver/Obsidian#7]
![capture](https://user-images.githubusercontent.com/23016064/34057019-a7f6f76e-e1d5-11e7-97b3-0ab81071158c.PNG)

![136538](https://user-images.githubusercontent.com/23016064/34057254-8675aed6-e1d6-11e7-9cad-f6f8ab30f13c.png) images/txt.png

**Comment by lamjed001** [comment]
sorry the problem at my server not by theme
the file name was mime.png at the last version :) and thank for you hard work
